FROM mysql:5.7


# TODO :: add remote application user / remove root wildcard access prior to production use
# RUN mysql -u root -psecret -e "GRANT ALL ON *.* to root@'%' IDENTIFIED BY 'secret';"
# RUN mysql -u root -psecret -e "FLUSH PRIVILEGES;"